return {
	override_enabled = true,
	settings_preset = "DST_CAVE", -- "SURVIVAL_TOGETHER", "MOD_MISSING", "SURVIVAL_TOGETHER_CLASSIC", "SURVIVAL_DEFAULT_PLUS", "COMPLETE_DARKNESS", "TERRARIA", "DST_CAVE", "DST_CAVE_PLUS", "TERRARIA_CAVE"
	worldgen_preset = "DST_CAVE", -- "SURVIVAL_TOGETHER", "MOD_MISSING", "SURVIVAL_TOGETHER_CLASSIC", "SURVIVAL_DEFAULT_PLUS", "COMPLETE_DARKNESS", "TERRARIA", "DST_CAVE", "DST_CAVE_PLUS", "TERRARIA_CAVE"
}
